const BUCKET='churchart-assets';
function cfg(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error('SUPABASE_URL ou SUPABASE_SECRET_KEY não configuradas na Vercel.');return{url,key,headers:{apikey:key,Authorization:`Bearer ${key}`}}}
async function rest(path,opt={}){const c=cfg();const r=await fetch(`${c.url}/rest/v1/${path}`,{...opt,headers:{...c.headers,'Content-Type':'application/json',...(opt.headers||{})}});const text=await r.text();let d=null;try{d=text?JSON.parse(text):null}catch{d=text}if(!r.ok)throw new Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
async function uploadDataUrl(dataUrl,path,mime){const c=cfg();const base64=dataUrl.split(',')[1];if(!base64)throw new Error('Arquivo inválido.');const buf=Buffer.from(base64,'base64');const r=await fetch(`${c.url}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{...c.headers,'Content-Type':mime||'application/octet-stream','x-upsert':'true'},body:buf});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.message||`Storage ${r.status}`)}return `${c.url}/storage/v1/object/public/${BUCKET}/${path}`}
function safeName(n='file'){return n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,100)}
module.exports=async function handler(req,res){try{const a=req.query.action;cfg();if(a==='bootstrap'){const [p,assets,gens]=await Promise.all([rest('church_profile?id=eq.default&select=*'),rest('church_assets?church_id=eq.default&select=*&order=created_at.desc'),rest('church_generations?church_id=eq.default&select=*&order=created_at.desc&limit=12')]);return res.json({profile:p?.[0]||null,assets:assets||[],generations:gens||[]})}
if(a==='save-profile'&&req.method==='POST'){const b=req.body||{};const d=await rest('church_profile?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify([{id:'default',name:b.name||'',address:b.address||''}])});return res.json({profile:d?.[0]})}
if(a==='upload-asset'&&req.method==='POST'){const b=req.body||{};const id=crypto.randomUUID();const ext=(b.name?.split('.').pop()||'bin').toLowerCase();const path=`default/${b.type||'asset'}/${id}-${safeName(b.name||`file.${ext}`)}`;const url=await uploadDataUrl(b.dataUrl,path,b.mimeType);const d=await rest('church_assets',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{id,church_id:'default',type:b.type||'graphic',name:b.name||'Asset',url,mime_type:b.mimeType||'',meta:b.meta||{},is_primary:false}])});return res.json({asset:d?.[0]})}
if(a==='delete-asset'&&req.method==='DELETE'){const id=req.body?.id;if(!id)throw new Error('ID ausente.');const rows=await rest(`church_assets?id=eq.${id}&select=*`);const asset=rows?.[0];if(asset){await rest(`church_assets?id=eq.${id}`,{method:'DELETE'});}return res.json({ok:true})}
if(a==='upload-generation'&&req.method==='POST'){const b=req.body||{};const id=crypto.randomUUID();const path=`default/generations/${Date.now()}-${id}.png`;const url=await uploadDataUrl(b.dataUrl,path,'image/png');return res.json({url})}
if(a==='save-generation'&&req.method==='POST'){const b=req.body||{};const d=await rest('church_generations',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{church_id:'default',format:b.format||'feed',images:b.images||[]}])});return res.json({generation:d?.[0]})}
return res.status(400).json({error:'Ação inválida.'});}catch(e){console.error('church-data',e);return res.status(500).json({error:e.message||'Erro no banco.'});}};
